runtime: go
api_version: go1
#env: flex

#automatic_scaling:
  #min_num_instances: 1

#[START env]
env_variables:
  # See https://godoc.org/github.com/lib/pq
  #
  # Replace INSTANCE_CONNECTION_NAME with the same value as in the
  # beta_settings section below.
  POSTGRES_CONNECTION: "user=postgres password=6CNvuFA1Ehp0NbDv dbname=postgres host=/cloudsql/go-app-221708:us-central1:testdb-1"
  CLOUDSQL_CONNECTION_NAME: "go-app-221708:us-central1:mysqldb" 
  CLOUDSQL_USER: "root"
  CLOUDSQL_PASSWORD: "3zta8jzgKnF6dNjI"
  CLOUDSQL_DATABASE: "testdb"
  #
  # If you're testing locally using the Cloud SQL proxy with TCP,
  # instead set this environment variable:
  # POSTGRES_CONNECTION="user=chikku password=123 dbname=goapp sslmode=disable"
#[END env]

#[START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
beta_settings:
  cloud_sql_instances: go-app-221708:us-central1:testdb-1
#[END cloudsql_settings]

handlers:
  - url: /api/validate
    script: router.go
    login: required
  - url: /api/file
    script: router.go
    login: required
  - url: /api/insert
    script: router.go
    login: required
  - url: /api/insertTestUsers
    script: router.go
    login: required



  - url: /insertPage
    script: router.go
    login: required
  - url: /updatePage
    script: router.go
    login: required
  - url: /validatePage
    script: router.go
    login: required
  - url: /uploadPage
    script: router.go
    login: required
  - url: /downloadPage
    script: router.go
    login: required
  - url: /loginPage
    script: router.go
    login: required
  - url: /adminPage
    script: router.go
    login: required
  - url: /premiumPage
    script: router.go
    login: required
  - url: /defaultPage
    script: router.go
    login: required
  - url: /profilePage
    script: router.go
    login: required


  - url: /createApplication
    script: router.go
    login: required
  - url: /api/insertApplicationIntoUser
    script: router.go
    login: required
  - url: /testapp01
    script: router.go
    login: required
  - url: /testapp02
    script: router.go
    login: required
  - url: /testapp03
    script: router.go
    login: required

  - url: /.*
    script: _go_app

  - url: /_ah/remote_api
    script: _go_app
